# Generated by Django 3.1.7 on 2021-03-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0002_area_order_product_producttype_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='allergen',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
