# Generated by Django 3.1.7 on 2021-03-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0003_auto_20210320_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roseleaf_app.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roseleaf_app.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roseleaf_app.member')),
            ],
        ),
    ]
