# Generated by Django 3.1.7 on 2021-03-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(to='roseleaf_app.Allergen'),
        ),
    ]
