# Generated by Django 3.1.7 on 2021-03-21 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0006_auto_20210321_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
    ]
