# Generated by Django 3.1.7 on 2021-03-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0007_remove_order_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='roseleaf_app.Product'),
        ),
    ]
