# Generated by Django 3.1.7 on 2021-03-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0009_auto_20210321_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='order_detail',
            field=models.ManyToManyField(to='roseleaf_app.OrderDetail'),
        ),
    ]
