# Generated by Django 3.1.7 on 2021-04-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0011_auto_20210406_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roseleaf_app.season'),
        ),
    ]
