# Generated by Django 3.1.7 on 2021-04-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0012_auto_20210406_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='season',
        ),
    ]
