# Generated by Django 3.1.7 on 2021-04-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0017_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roseleaf_app.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
