# Generated by Django 3.1.7 on 2021-06-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roseleaf_app', '0021_orderdetail_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='supplier',
        ),
    ]
